// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkjTJP9reer9xyp8XGoeref0TOZCdKzvw',
    appId: '1:727374167473:web:d4793c9bc61c981cf89190',
    messagingSenderId: '727374167473',
    projectId: 'relaxio-1c3b3',
    authDomain: 'relaxio-1c3b3.firebaseapp.com',
    storageBucket: 'relaxio-1c3b3.appspot.com',
    measurementId: 'G-5SQ0SJ1QJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfM5CL-f95ajvbLL-99_0wDImquPOSqk',
    appId: '1:727374167473:android:260bfb152d8455f5f89190',
    messagingSenderId: '727374167473',
    projectId: 'relaxio-1c3b3',
    storageBucket: 'relaxio-1c3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdYDL63iZv6gbSGK8ZQ4Fatt8XvxcBEg',
    appId: '1:727374167473:ios:ed119684e5cd9251f89190',
    messagingSenderId: '727374167473',
    projectId: 'relaxio-1c3b3',
    storageBucket: 'relaxio-1c3b3.appspot.com',
    iosBundleId: 'com.example.relaxio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdYDL63iZv6gbSGK8ZQ4Fatt8XvxcBEg',
    appId: '1:727374167473:ios:00c6a8fbe5ec11f0f89190',
    messagingSenderId: '727374167473',
    projectId: 'relaxio-1c3b3',
    storageBucket: 'relaxio-1c3b3.appspot.com',
    iosBundleId: 'com.example.relaxio.RunnerTests',
  );
}
